# The hot table: `contributions`, declaratively RANGE-partitioned by `cycle`.
#
# Why partition by cycle?
#   * Campaign-finance queries are almost always scoped to one election cycle.
#     Range partitioning lets the planner *prune* every partition but the one(s)
#     a query touches — `EXPLAIN` shows a single partition scanned, so a billion
#     rows behave like the ~hundreds of millions in one cycle.
#   * Each cycle closes and goes cold. A closed cycle is one partition you can
#     reindex, VACUUM, detach, or move to cheaper storage independently — no
#     giant monolithic table to wrangle.
#
# Partitioning rules in PostgreSQL we must respect here:
#   * The partition key (`cycle`) MUST be part of the PRIMARY KEY, so the PK is
#     composite: (id, cycle). `id` is a BIGINT identity, unique within the table
#     by construction; Active Record still treats `id` as the primary key.
#   * Indexes/constraints are declared on the parent and propagate to partitions.
#
# This migration is intentionally raw SQL (`execute`): schema.rb cannot express
# PARTITION BY, which is exactly why config.active_record.schema_format = :sql.
class CreateContributionsPartitioned < ActiveRecord::Migration[7.2]
  # Cycles we provision partitions for up front. Adding a future cycle is one
  # more CREATE TABLE ... PARTITION OF (see AddCycle migrations / runbook).
  CYCLES = [2022, 2024, 2026].freeze

  def up
    execute(<<~SQL)
      CREATE TABLE contributions (
        id          bigint    GENERATED BY DEFAULT AS IDENTITY,
        donor_id    bigint    NOT NULL,
        committee_id bigint   NOT NULL,
        cycle       integer   NOT NULL,
        amount      numeric(12,2) NOT NULL,
        occurred_on date      NOT NULL,
        employer    varchar,
        occupation  varchar,
        memo        varchar,
        created_at  timestamp(6) NOT NULL DEFAULT now(),
        updated_at  timestamp(6) NOT NULL DEFAULT now(),
        -- The partition key must be in the PK; (id, cycle) is the composite PK.
        PRIMARY KEY (id, cycle),
        -- FEC contributions are positive amounts; reject zero/negative at the DB.
        CONSTRAINT chk_contributions_amount_positive CHECK (amount > 0),
        -- A row must land in a real partition; the key must match its cycle.
        CONSTRAINT chk_contributions_cycle CHECK (cycle IN (2022, 2024, 2026))
      ) PARTITION BY RANGE (cycle);
    SQL

    # One partition per cycle. RANGE bounds are [from, to) — inclusive lower,
    # exclusive upper — so cycle=2024 lands in the [2024,2025) partition.
    CYCLES.each do |cycle|
      execute(<<~SQL)
        CREATE TABLE contributions_#{cycle}
          PARTITION OF contributions
          FOR VALUES FROM (#{cycle}) TO (#{cycle + 1});
      SQL
    end

    # Foreign keys: declared on the parent, enforced per-partition by Postgres.
    execute(<<~SQL)
      ALTER TABLE contributions
        ADD CONSTRAINT fk_contributions_donor
        FOREIGN KEY (donor_id) REFERENCES donors (id);
      ALTER TABLE contributions
        ADD CONSTRAINT fk_contributions_committee
        FOREIGN KEY (committee_id) REFERENCES committees (id);
    SQL

    # The covering index for the hot rollup query. The rollup groups by
    # (cycle, committee_id) and needs amount + donor_id to compute total raised,
    # distinct donors, and the $200 itemized/unitemized split — all from the
    # index, so the per-partition scan is index-only (no heap fetch).
    #   cycle leads → combined with partition pruning the planner touches exactly
    #   one partition's index; committee_id next → the GROUP BY key; amount and
    #   donor_id INCLUDEd → the aggregates are answered from the index payload.
    execute(<<~SQL)
      CREATE INDEX idx_contributions_rollup
        ON contributions (cycle, committee_id)
        INCLUDE (amount, donor_id);
    SQL

    # Secondary access path: by donor within a cycle (donor history lookups).
    execute(<<~SQL)
      CREATE INDEX idx_contributions_donor
        ON contributions (cycle, donor_id);
    SQL
  end

  def down
    execute "DROP TABLE IF EXISTS contributions CASCADE;"
  end
end
