"""Deterministic file templates for the team's standard platform setup.

Every function takes a normalized ``ServiceSpec`` and returns the exact text of
one generated file. No randomness, no I/O, no clock — the same spec always
produces byte-identical output, which is what makes the scaffolder reviewable in
a PR and reproducible in the eval.

The k8s manifest is rendered from the same ``deploy/k8s/base`` shape the
platform ships (Namespace + Deployment + Service + HPA + PodDisruptionBudget +
readiness/liveness probes), so a scaffolded service inherits the base contract
rather than reinventing it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from baseplate.scaffold import ServiceSpec

# Per-language base image + container port the standard platform setup uses.
_BASE_IMAGE = {
    "python": "python:3.11-slim",
    "node": "node:20-slim",
    "go": "golang:1.22-alpine",
}
_PORT = 8080


def dockerfile(spec: ServiceSpec) -> str:
    base = _BASE_IMAGE[spec.language]
    install = {
        "python": "RUN pip install --no-cache-dir -r requirements.txt",
        "node": "RUN npm ci --omit=dev",
        "go": "RUN go build -o /app/server ./...",
    }[spec.language]
    cmd = {
        "python": 'CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT}"]',
        "node": 'CMD ["node", "server.js"]',
        "go": 'CMD ["/app/server"]',
    }[spec.language]
    return f"""# Generated by baseplate — standard Dockerfile for {spec.name}.
# Single-stage, non-root, PORT-driven, with a /health contract the platform
# probes. Replace the COPY/install lines with your service's real sources.
FROM {base}
RUN useradd --create-home --uid 1001 app 2>/dev/null || adduser -D -u 1001 app
WORKDIR /app
COPY . /app/
{install}
ENV PORT={_PORT}
USER app
EXPOSE {_PORT}
{cmd}
"""


def k8s_manifest(spec: ServiceSpec) -> str:
    """Render the base Deployment/Service/HPA/PDB for this service.

    Mirrors ``deploy/k8s/base`` exactly so onboarding a service is "fill in the
    name" rather than "author Kubernetes from scratch".
    """
    db_env = ""
    if spec.needs_db:
        db_env = f"""
            # Postgres from the Terraform `service` module's RDS wiring. The
            # secret is mounted by IRSA; never a long-lived key.
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {spec.name}-db
                  key: DATABASE_URL"""

    service_block = ""
    if spec.exposes_http:
        service_block = f"""---
apiVersion: v1
kind: Service
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  selector: {{ app: {spec.name} }}
  ports:
    - port: 80
      targetPort: {_PORT}
"""

    probes = ""
    if spec.exposes_http:
        probes = f"""
          readinessProbe:
            httpGet: {{ path: /health, port: {_PORT} }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: {{ path: /health, port: {_PORT} }}
            initialDelaySeconds: 10
            periodSeconds: 15"""

    return f"""# Generated by baseplate from deploy/k8s/base for service "{spec.name}".
# Inherits the platform's standard contract: non-root, resource limits, probes,
# autoscaling, and a PodDisruptionBudget so rollouts/drains keep a quorum.
apiVersion: v1
kind: Namespace
metadata:
  name: {spec.name}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {spec.name}
  namespace: {spec.name}
  labels: {{ app: {spec.name}, platform-managed: "true" }}
spec:
  replicas: 2
  selector:
    matchLabels: {{ app: {spec.name} }}
  template:
    metadata:
      labels: {{ app: {spec.name} }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: app
          image: ECR_REPO/{spec.name}:GIT_SHA   # set by the CI/CD pipeline
          ports:
            - containerPort: {_PORT}
          env:
            - name: PORT
              value: "{_PORT}"{db_env}
          resources:
            requests: {{ cpu: 100m, memory: 128Mi }}
            limits:   {{ cpu: "1",  memory: 256Mi }}{probes}
{service_block}---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {spec.name}
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {{ type: Utilization, averageUtilization: 65 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ app: {spec.name} }}
"""


def argocd_application(spec: ServiceSpec) -> str:
    return f"""# Generated by baseplate — Argo CD Application for {spec.name}.
# Drop this file in deploy/argocd/ and the ApplicationSet (or app-of-apps) picks
# it up: the repo is the source of truth, the cluster follows.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {spec.name}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ORG/REPO.git
    targetRevision: main
    path: services/{spec.name}/deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: {spec.name}
  syncPolicy:
    automated: {{ prune: true, selfHeal: true }}
    syncOptions:
      - CreateNamespace=true
"""


def terraform_service(spec: ServiceSpec) -> str:
    """Invoke the reusable `service` module (ECR + IRSA + namespace [+ RDS])."""
    db_line = ("  needs_db     = true   # provisions an RDS Postgres "
               "+ a scoped IRSA secret")
    if not spec.needs_db:
        db_line = "  needs_db     = false"
    return f"""# Generated by baseplate — invokes the platform's reusable \
`service` module.
# The module owns ECR, IRSA (scoped, keyless pod identity), the k8s namespace,
# and (when needs_db) an RDS Postgres with the connection string in Secrets
# Manager. A new service is one module block, not a hand-rolled stack.
module "{_tf_name(spec.name)}" {{
  source       = "../modules/service"
  name         = "{spec.name}"
  environment  = var.environment
  exposes_http = {str(spec.exposes_http).lower()}
{db_line}

  oidc_provider_arn = module.eks.oidc_provider_arn
  vpc_id            = module.vpc.vpc_id
  private_subnets   = module.vpc.private_subnets
}}

output "{_tf_name(spec.name)}_ecr_url" {{
  value = module.{_tf_name(spec.name)}.ecr_repository_url
}}
"""


def ci_workflow(spec: ServiceSpec) -> str:
    """The standard CI/CD pipeline, specialized for this service's language."""
    test_step = {
        "python": "          python -m pip install -r requirements.txt\n"
                  "          python -m pytest -q",
        "node": "          npm ci\n          npm test",
        "go": "          go test ./...",
    }[spec.language]
    return f"""# Generated by baseplate — the standard CI/CD pipeline for {spec.name}.
# OIDC keyless auth (no static AWS keys), build -> test -> scan -> deploy, then a
# post-deploy smoke gate that rolls back on failure. Same shape for every
# service on the standard platform setup; only the language test step differs.
name: {spec.name}-ci
on:
  push: {{ branches: [main] }}
  pull_request: {{}}

permissions:
  contents: read
  id-token: write   # OIDC: assume the deploy role, no long-lived secrets

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
{test_step}

      - name: Build image
        run: docker build -t "$IMAGE:$GITHUB_SHA" .

      - name: Scan image (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "$IMAGE:${{{{ github.sha }}}}"
          severity: HIGH,CRITICAL
          exit-code: "1"

      - name: Auth to AWS (OIDC, keyless)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::ACCOUNT:role/{spec.name}-deploy
          aws-region: us-east-1

      - name: Push + deploy (GitOps bumps the image tag)
        run: ./platform/deploy.sh {spec.name} "$GITHUB_SHA"

      - name: Post-deploy smoke gate (rollback on failure)
        run: ./platform/smoke.sh {spec.name} || ./platform/rollback.sh {spec.name}
"""


def slo_stub(spec: ServiceSpec) -> str:
    """A service-health target file: availability + latency, plus burn-rate alerts."""
    extra = ""
    if spec.exposes_http:
        extra = """
  - name: latency-p99
    measures: 99th-percentile request latency < 300ms
    objective: 99.0
    window: 30d"""
    freshness = ""
    if spec.needs_db:
        freshness = """
  - name: data-freshness
    measures: ratio of records updated within the freshness window
    objective: 99.0
    window: 30d"""
    return f"""# Generated by baseplate — service-health targets for {spec.name}.
# Wire these into your monitoring tool as reliability targets with multi-window
# burn-rate alerts. Start conservative and tighten as you earn the error budget.
# Each target names what it measures, the goal, and the time window.
service: {spec.name}
health_targets:
  - name: availability
    measures: ratio of non-5xx (successful) responses
    objective: 99.5        # ~3.6h error budget / 30d
    window: 30d{extra}{freshness}
burn_rate_alerts:
  - window: 1h
    threshold: 14.4        # fast burn: paging
  - window: 6h
    threshold: 6.0         # slow burn: ticket
"""


def readme(spec: ServiceSpec) -> str:
    """A README.md with deployment instructions, tailored to the generated files."""
    db_line = ("- a managed **Postgres** database (provisioned by the Terraform "
               "module)\n") if spec.needs_db else ""
    http_line = (f"- serves HTTP on port **{_PORT}** (health check at `/health`)\n"
                 if spec.exposes_http else "- a background/worker service "
                 "(no HTTP endpoint)\n")
    k8s_path = f"deploy/k8s/{spec.name}.yaml"
    argo_path = f"deploy/argocd/{spec.name}.yaml"
    tf_path = f"deploy/terraform/{spec.name}.tf"
    db_extra = ", Postgres" if spec.needs_db else ""
    dq_extra = ", data quality" if spec.needs_db else ""
    bundle_table = "\n".join([
        "| File | What it is |",
        "|------|------------|",
        "| `Dockerfile` | Packages the service into a container image "
        "(non-root). |",
        f"| `{k8s_path}` | Kubernetes Deployment + Service: replicas, health "
        "probes, resource limits, autoscaling. |",
        f"| `{argo_path}` | Argo CD Application — GitOps: keeps the cluster in "
        "sync with this repo. |",
        f"| `{tf_path}` | Terraform: the AWS resources the service needs "
        f"(registry, network{db_extra}). |",
        "| `.github/workflows/ci.yml` | CI/CD pipeline: build → test → scan → "
        "deploy → smoke-test → roll back on failure. |",
        f"| `slo.yaml` | Service-health targets (availability, latency{dq_extra}) "
        "with burn-rate alerts. |",
    ])
    return f"""# {spec.name}

Generated by **baseplate** from a plain-English description. A `{spec.language}`
service with the standard deploy setup already wired up:

{http_line}{db_line}
The model only read the spec from your description; every file below was produced
by deterministic code, so review it like any pull request before you apply it.

## What's in this bundle

{bundle_table}

## Deploy it

> These files are **illustrative** — they target a standard AWS/EKS platform.
> Review and adjust registry names, account IDs, and the cluster context for your
> environment before applying.

1. **Provision infrastructure** (Terraform):
   ```bash
   cd deploy/terraform && terraform init && terraform plan && terraform apply
   ```
2. **Build & push the image**:
   ```bash
   docker build -t <your-registry>/{spec.name}:$(git rev-parse --short HEAD) .
   docker push <your-registry>/{spec.name}:$(git rev-parse --short HEAD)
   ```
3. **Deploy to Kubernetes** — directly:
   ```bash
   kubectl apply -f {k8s_path}
   ```
   …or via **GitOps** (recommended): commit `{argo_path}` and let Argo CD sync it.
4. **CI/CD**: `.github/workflows/ci.yml` runs the full pipeline on every push to
   `main` — build, test, vulnerability scan, deploy, post-deploy smoke test, and
   automatic rollback if the smoke test fails. No manual steps after step 1.
5. **Monitor**: load `slo.yaml` into your monitoring tool as the service's
   reliability targets and burn-rate alerts.

---
*Generated by baseplate · the model proposes the spec, code produces the files.*
"""


def _tf_name(name: str) -> str:
    """Terraform module/identifier labels can't contain hyphens."""
    return name.replace("-", "_")
