"""Deterministic paved-road file templates.

Every function takes a normalized ``ServiceSpec`` and returns the exact text of
one generated file. No randomness, no I/O, no clock — the same spec always
produces byte-identical output, which is what makes the scaffolder reviewable in
a PR and reproducible in the eval.

The k8s manifest is rendered from the same ``deploy/k8s/base`` shape the
platform ships (Namespace + Deployment + Service + HPA + PodDisruptionBudget +
readiness/liveness probes), so a scaffolded service inherits the base contract
rather than reinventing it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from baseplate.scaffold import ServiceSpec

# Per-language base image + container port the paved road standardizes on.
_BASE_IMAGE = {
    "python": "python:3.11-slim",
    "node": "node:20-slim",
    "go": "golang:1.22-alpine",
}
_PORT = 8080


def dockerfile(spec: ServiceSpec) -> str:
    base = _BASE_IMAGE[spec.language]
    install = {
        "python": "RUN pip install --no-cache-dir -r requirements.txt",
        "node": "RUN npm ci --omit=dev",
        "go": "RUN go build -o /app/server ./...",
    }[spec.language]
    cmd = {
        "python": 'CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT}"]',
        "node": 'CMD ["node", "server.js"]',
        "go": 'CMD ["/app/server"]',
    }[spec.language]
    return f"""# Generated by baseplate — paved-road Dockerfile for {spec.name}.
# Single-stage, non-root, PORT-driven, with a /health contract the platform
# probes. Replace the COPY/install lines with your service's real sources.
FROM {base}
RUN useradd --create-home --uid 1001 app 2>/dev/null || adduser -D -u 1001 app
WORKDIR /app
COPY . /app/
{install}
ENV PORT={_PORT}
USER app
EXPOSE {_PORT}
{cmd}
"""


def k8s_manifest(spec: ServiceSpec) -> str:
    """Render the base Deployment/Service/HPA/PDB for this service.

    Mirrors ``deploy/k8s/base`` exactly so onboarding a service is "fill in the
    name" rather than "author Kubernetes from scratch".
    """
    db_env = ""
    if spec.needs_db:
        db_env = f"""
            # Postgres from the Terraform `service` module's RDS wiring. The
            # secret is mounted by IRSA; never a long-lived key.
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {spec.name}-db
                  key: DATABASE_URL"""

    service_block = ""
    if spec.exposes_http:
        service_block = f"""---
apiVersion: v1
kind: Service
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  selector: {{ app: {spec.name} }}
  ports:
    - port: 80
      targetPort: {_PORT}
"""

    probes = ""
    if spec.exposes_http:
        probes = f"""
          readinessProbe:
            httpGet: {{ path: /health, port: {_PORT} }}
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet: {{ path: /health, port: {_PORT} }}
            initialDelaySeconds: 10
            periodSeconds: 15"""

    return f"""# Generated by baseplate from deploy/k8s/base for service "{spec.name}".
# Inherits the paved-road contract: non-root, resource limits, probes, HPA, and
# a PodDisruptionBudget so rollouts/drains keep a quorum.
apiVersion: v1
kind: Namespace
metadata:
  name: {spec.name}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {spec.name}
  namespace: {spec.name}
  labels: {{ app: {spec.name}, paved-road: "true" }}
spec:
  replicas: 2
  selector:
    matchLabels: {{ app: {spec.name} }}
  template:
    metadata:
      labels: {{ app: {spec.name} }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: app
          image: ECR_REPO/{spec.name}:GIT_SHA   # set by the golden CI pipeline
          ports:
            - containerPort: {_PORT}
          env:
            - name: PORT
              value: "{_PORT}"{db_env}
          resources:
            requests: {{ cpu: 100m, memory: 128Mi }}
            limits:   {{ cpu: "1",  memory: 256Mi }}{probes}
{service_block}---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {spec.name}
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: {{ type: Utilization, averageUtilization: 65 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {spec.name}
  namespace: {spec.name}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ app: {spec.name} }}
"""


def argocd_application(spec: ServiceSpec) -> str:
    return f"""# Generated by baseplate — Argo CD Application for {spec.name}.
# Drop this file in deploy/argocd/ and the ApplicationSet (or app-of-apps) picks
# it up: the repo is the source of truth, the cluster follows.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {spec.name}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ORG/REPO.git
    targetRevision: main
    path: services/{spec.name}/deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: {spec.name}
  syncPolicy:
    automated: {{ prune: true, selfHeal: true }}
    syncOptions:
      - CreateNamespace=true
"""


def terraform_service(spec: ServiceSpec) -> str:
    """Invoke the reusable `service` module (ECR + IRSA + namespace [+ RDS])."""
    db_line = ("  needs_db     = true   # provisions an RDS Postgres "
               "+ a scoped IRSA secret")
    if not spec.needs_db:
        db_line = "  needs_db     = false"
    return f"""# Generated by baseplate — invokes the platform's reusable \
`service` module.
# The module owns ECR, IRSA (scoped, keyless pod identity), the k8s namespace,
# and (when needs_db) an RDS Postgres with the connection string in Secrets
# Manager. A new service is one module block, not a hand-rolled stack.
module "{_tf_name(spec.name)}" {{
  source       = "../modules/service"
  name         = "{spec.name}"
  environment  = var.environment
  exposes_http = {str(spec.exposes_http).lower()}
{db_line}

  oidc_provider_arn = module.eks.oidc_provider_arn
  vpc_id            = module.vpc.vpc_id
  private_subnets   = module.vpc.private_subnets
}}

output "{_tf_name(spec.name)}_ecr_url" {{
  value = module.{_tf_name(spec.name)}.ecr_repository_url
}}
"""


def ci_workflow(spec: ServiceSpec) -> str:
    """The golden CI/CD pipeline, specialized for this service's language."""
    test_step = {
        "python": "          python -m pip install -r requirements.txt\n"
                  "          python -m pytest -q",
        "node": "          npm ci\n          npm test",
        "go": "          go test ./...",
    }[spec.language]
    return f"""# Generated by baseplate — the golden CI/CD pipeline for {spec.name}.
# OIDC keyless auth (no static AWS keys), build -> test -> scan -> deploy, then a
# post-deploy smoke gate that rolls back on failure. Same shape for every
# service on the paved road; only the language test step differs.
name: {spec.name}-ci
on:
  push: {{ branches: [main] }}
  pull_request: {{}}

permissions:
  contents: read
  id-token: write   # OIDC: assume the deploy role, no long-lived secrets

jobs:
  ship:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
{test_step}

      - name: Build image
        run: docker build -t "$IMAGE:$GITHUB_SHA" .

      - name: Scan image (fail on HIGH/CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "$IMAGE:${{{{ github.sha }}}}"
          severity: HIGH,CRITICAL
          exit-code: "1"

      - name: Auth to AWS (OIDC, keyless)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::ACCOUNT:role/{spec.name}-deploy
          aws-region: us-east-1

      - name: Push + deploy (GitOps bumps the image tag)
        run: ./platform/deploy.sh {spec.name} "$GITHUB_SHA"

      - name: Post-deploy smoke gate (rollback on failure)
        run: ./platform/smoke.sh {spec.name} || ./platform/rollback.sh {spec.name}
"""


def slo_stub(spec: ServiceSpec) -> str:
    """A Datadog-style SLO stub: availability + latency, plus a burn-rate alert."""
    extra = ""
    if spec.exposes_http:
        extra = """
  - name: latency-p99
    sli: p99 request latency < 300ms
    objective: 99.0
    window: 30d"""
    freshness = ""
    if spec.needs_db:
        freshness = """
  - name: data-freshness
    sli: ratio of records updated within the freshness window
    objective: 99.0
    window: 30d"""
    return f"""# Generated by baseplate — SLO stub for {spec.name}.
# Wire these into Datadog as SLOs with multi-window burn-rate alerts. Start
# conservative and tighten as you earn the error budget. See docs/observability.md.
service: {spec.name}
slos:
  - name: availability
    sli: ratio of non-5xx responses
    objective: 99.5        # ~3.6h error budget / 30d
    window: 30d{extra}{freshness}
burn_rate_alerts:
  - window: 1h
    threshold: 14.4        # fast burn: paging
  - window: 6h
    threshold: 6.0         # slow burn: ticket
"""


def _tf_name(name: str) -> str:
    """Terraform module/identifier labels can't contain hyphens."""
    return name.replace("-", "_")
