SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ar_internal_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ar_internal_metadata (
    key character varying NOT NULL,
    value character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: committees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.committees (
    id bigint NOT NULL,
    fec_id character varying NOT NULL,
    name character varying NOT NULL,
    committee_type character varying NOT NULL,
    party character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: committees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.committees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: committees_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.committees_id_seq OWNED BY public.committees.id;


--
-- Name: contributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributions (
    id bigint NOT NULL,
    donor_id bigint NOT NULL,
    committee_id bigint NOT NULL,
    cycle integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    occurred_on date NOT NULL,
    employer character varying,
    occupation character varying,
    memo character varying,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_contributions_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT chk_contributions_cycle CHECK ((cycle = ANY (ARRAY[2022, 2024, 2026])))
)
PARTITION BY RANGE (cycle);


--
-- Name: contributions_2022; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributions_2022 (
    id bigint NOT NULL,
    donor_id bigint NOT NULL,
    committee_id bigint NOT NULL,
    cycle integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    occurred_on date NOT NULL,
    employer character varying,
    occupation character varying,
    memo character varying,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_contributions_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT chk_contributions_cycle CHECK ((cycle = ANY (ARRAY[2022, 2024, 2026])))
);


--
-- Name: contributions_2024; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributions_2024 (
    id bigint NOT NULL,
    donor_id bigint NOT NULL,
    committee_id bigint NOT NULL,
    cycle integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    occurred_on date NOT NULL,
    employer character varying,
    occupation character varying,
    memo character varying,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_contributions_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT chk_contributions_cycle CHECK ((cycle = ANY (ARRAY[2022, 2024, 2026])))
);


--
-- Name: contributions_2026; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contributions_2026 (
    id bigint NOT NULL,
    donor_id bigint NOT NULL,
    committee_id bigint NOT NULL,
    cycle integer NOT NULL,
    amount numeric(12,2) NOT NULL,
    occurred_on date NOT NULL,
    employer character varying,
    occupation character varying,
    memo character varying,
    created_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_contributions_amount_positive CHECK ((amount > (0)::numeric)),
    CONSTRAINT chk_contributions_cycle CHECK ((cycle = ANY (ARRAY[2022, 2024, 2026])))
);


--
-- Name: contributions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contributions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contributions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.donors (
    id bigint NOT NULL,
    full_name character varying NOT NULL,
    city character varying,
    state character varying(2),
    zip character varying(10),
    employer character varying,
    occupation character varying,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: donors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.donors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: donors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.donors_id_seq OWNED BY public.donors.id;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: contributions_2022; Type: TABLE ATTACH; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions ATTACH PARTITION public.contributions_2022 FOR VALUES FROM (2022) TO (2023);


--
-- Name: contributions_2024; Type: TABLE ATTACH; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions ATTACH PARTITION public.contributions_2024 FOR VALUES FROM (2024) TO (2025);


--
-- Name: contributions_2026; Type: TABLE ATTACH; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions ATTACH PARTITION public.contributions_2026 FOR VALUES FROM (2026) TO (2027);


--
-- Name: committees id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.committees ALTER COLUMN id SET DEFAULT nextval('public.committees_id_seq'::regclass);


--
-- Name: donors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donors ALTER COLUMN id SET DEFAULT nextval('public.donors_id_seq'::regclass);


--
-- Name: ar_internal_metadata ar_internal_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ar_internal_metadata
    ADD CONSTRAINT ar_internal_metadata_pkey PRIMARY KEY (key);


--
-- Name: committees committees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.committees
    ADD CONSTRAINT committees_pkey PRIMARY KEY (id);


--
-- Name: contributions contributions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions
    ADD CONSTRAINT contributions_pkey PRIMARY KEY (id, cycle);


--
-- Name: contributions_2022 contributions_2022_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions_2022
    ADD CONSTRAINT contributions_2022_pkey PRIMARY KEY (id, cycle);


--
-- Name: contributions_2024 contributions_2024_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions_2024
    ADD CONSTRAINT contributions_2024_pkey PRIMARY KEY (id, cycle);


--
-- Name: contributions_2026 contributions_2026_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contributions_2026
    ADD CONSTRAINT contributions_2026_pkey PRIMARY KEY (id, cycle);


--
-- Name: donors donors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.donors
    ADD CONSTRAINT donors_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: idx_contributions_rollup; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contributions_rollup ON ONLY public.contributions USING btree (cycle, committee_id) INCLUDE (amount, donor_id);


--
-- Name: contributions_2022_cycle_committee_id_amount_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2022_cycle_committee_id_amount_donor_id_idx ON public.contributions_2022 USING btree (cycle, committee_id) INCLUDE (amount, donor_id);


--
-- Name: idx_contributions_donor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contributions_donor ON ONLY public.contributions USING btree (cycle, donor_id);


--
-- Name: contributions_2022_cycle_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2022_cycle_donor_id_idx ON public.contributions_2022 USING btree (cycle, donor_id);


--
-- Name: contributions_2024_cycle_committee_id_amount_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2024_cycle_committee_id_amount_donor_id_idx ON public.contributions_2024 USING btree (cycle, committee_id) INCLUDE (amount, donor_id);


--
-- Name: contributions_2024_cycle_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2024_cycle_donor_id_idx ON public.contributions_2024 USING btree (cycle, donor_id);


--
-- Name: contributions_2026_cycle_committee_id_amount_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2026_cycle_committee_id_amount_donor_id_idx ON public.contributions_2026 USING btree (cycle, committee_id) INCLUDE (amount, donor_id);


--
-- Name: contributions_2026_cycle_donor_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX contributions_2026_cycle_donor_id_idx ON public.contributions_2026 USING btree (cycle, donor_id);


--
-- Name: index_committees_on_fec_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_committees_on_fec_id ON public.committees USING btree (fec_id);


--
-- Name: index_donors_on_state_and_city; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_donors_on_state_and_city ON public.donors USING btree (state, city);


--
-- Name: contributions_2022_cycle_committee_id_amount_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_rollup ATTACH PARTITION public.contributions_2022_cycle_committee_id_amount_donor_id_idx;


--
-- Name: contributions_2022_cycle_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_donor ATTACH PARTITION public.contributions_2022_cycle_donor_id_idx;


--
-- Name: contributions_2022_pkey; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.contributions_pkey ATTACH PARTITION public.contributions_2022_pkey;


--
-- Name: contributions_2024_cycle_committee_id_amount_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_rollup ATTACH PARTITION public.contributions_2024_cycle_committee_id_amount_donor_id_idx;


--
-- Name: contributions_2024_cycle_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_donor ATTACH PARTITION public.contributions_2024_cycle_donor_id_idx;


--
-- Name: contributions_2024_pkey; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.contributions_pkey ATTACH PARTITION public.contributions_2024_pkey;


--
-- Name: contributions_2026_cycle_committee_id_amount_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_rollup ATTACH PARTITION public.contributions_2026_cycle_committee_id_amount_donor_id_idx;


--
-- Name: contributions_2026_cycle_donor_id_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_contributions_donor ATTACH PARTITION public.contributions_2026_cycle_donor_id_idx;


--
-- Name: contributions_2026_pkey; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.contributions_pkey ATTACH PARTITION public.contributions_2026_pkey;


--
-- Name: contributions fk_contributions_committee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.contributions
    ADD CONSTRAINT fk_contributions_committee FOREIGN KEY (committee_id) REFERENCES public.committees(id);


--
-- Name: contributions fk_contributions_donor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.contributions
    ADD CONSTRAINT fk_contributions_donor FOREIGN KEY (donor_id) REFERENCES public.donors(id);


--
-- PostgreSQL database dump complete
--

SET search_path TO "$user", public;

INSERT INTO "schema_migrations" (version) VALUES
('20260101000003'),
('20260101000002'),
('20260101000001');

